var mongoose = require("mongoose");

class Database{
    constructor(){
        this.conectar();
    }

    conectar(){
        mongoose.connect(`mongodb://zaden:zaden_Z9@ds115971.mlab.com:15971/heroku_d2srm201`, { useNewUrlParser: true })
        .then(()=>{
            console.log("Se conectó a la base de datos remota.");
            cargarUsuariosPrueba();
        })
        .catch(error=>{
            console.error(JSON.stringify(error));   
        });
    }

    cargarUsuariosPrueba(){
        var data = [
            {"nombre": "Christian", "apellido": "Shields", "genero": "Masculino", "correo": "turpis.vitae@insodaleselit.co.uk", "usuario": "Kuame Vang", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "349-3375 A Road", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Gage", "apellido": "Delgado", "genero": "Helicóptero Apache de Combate", "correo": "at.sem@sollicitudinadipiscing.net", "usuario": "Ulric Anderson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "226-3648 Elit. Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Ivy", "apellido": "Oconnor", "genero": "Helicóptero Apache de Combate", "correo": "a.magna@est.net", "usuario": "Dora Cantu", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "611-1034 Dapibus Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Zelenia", "apellido": "White", "genero": "Femenino", "correo": "Nulla.tempor@bibendumsed.net", "usuario": "Jason Gardner", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #659-811 Sed Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Maia", "apellido": "Ruiz", "genero": "Masculino", "correo": "diam@adipiscingelitCurabitur.net", "usuario": "Mia Battle", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "3342 Egestas Rd.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Omar", "apellido": "Brock", "genero": "Helicóptero Apache de Combate", "correo": "dignissim.magna.a@Ut.edu", "usuario": "Gemma Everett", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "794-8503 Eleifend, St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Hector", "apellido": "Campbell", "genero": "Masculino", "correo": "rhoncus.Donec@malesuadafringilla.com", "usuario": "Benedict Love", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #846-6251 Nullam Rd.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Rhiannon", "apellido": "Dennis", "genero": "Masculino", "correo": "erat.eget.tincidunt@hymenaeos.edu", "usuario": "Dominic Suarez", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 398, 2314 Justo. St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Penelope", "apellido": "Decker", "genero": "Femenino", "correo": "ipsum@enimNuncut.edu", "usuario": "Jolie Buckley", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "3881 Eget Avenue", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Colt", "apellido": "Aguirre", "genero": "Femenino", "correo": "magnis.dis.parturient@aliquet.org", "usuario": "Trevor Collier", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 970, 3417 Ut St.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Kadeem", "apellido": "Mosley", "genero": "Masculino", "correo": "Nam.nulla.magna@dolordapibusgravida.ca", "usuario": "Ignacia Vang", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 521, 955 Pede. Rd.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Signe", "apellido": "Pierce", "genero": "Helicóptero Apache de Combate", "correo": "sed.pede@eratvolutpatNulla.net", "usuario": "Rooney Coffey", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "8257 Primis Road", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Merritt", "apellido": "Kaufman", "genero": "Masculino", "correo": "scelerisque@tincidunt.co.uk", "usuario": "Judith Berger", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "330-5181 Nibh. Av.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Teegan", "apellido": "Henderson", "genero": "Masculino", "correo": "feugiat@tincidunt.co.uk", "usuario": "Harrison Patterson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #366-6396 Augue St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Sandra", "apellido": "Mcfarland", "genero": "Masculino", "correo": "dis.parturient@Fuscefermentum.com", "usuario": "MacKensie Larson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "692-2379 Aliquam St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Brent", "apellido": "Newton", "genero": "Helicóptero Apache de Combate", "correo": "venenatis.vel.faucibus@velit.com", "usuario": "Shana Shaffer", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "477-1527 Consequat, Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Gretchen", "apellido": "Michael", "genero": "Masculino", "correo": "sit.amet.massa@turpisIn.com", "usuario": "Christian Guerra", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "880-5287 Tincidunt Av.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Rhona", "apellido": "Thompson", "genero": "Masculino", "correo": "Maecenas.ornare.egestas@leoin.net", "usuario": "Fleur Bird", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "335-8319 Magna. Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Ethan", "apellido": "Day", "genero": "Helicóptero Apache de Combate", "correo": "mauris.elit.dictum@nullaDonecnon.ca", "usuario": "Kiayada Mack", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "747-7021 Amet, St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Nicole", "apellido": "Campos", "genero": "Helicóptero Apache de Combate", "correo": "sapien@ullamcorper.org", "usuario": "Sonia Parks", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #678-7575 Morbi Street", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Naomi", "apellido": "Meyer", "genero": "Femenino", "correo": "nunc@dictumsapienAenean.net", "usuario": "Yvonne Rodgers", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "178-4653 Est, Rd.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Ali", "apellido": "Lowery", "genero": "Femenino", "correo": "nulla.In@sed.net", "usuario": "Joan Conrad", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "6122 Imperdiet Street", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Ira", "apellido": "Duran", "genero": "Femenino", "correo": "blandit.Nam@semNulla.org", "usuario": "Adria Hatfield", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "307 In Av.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Kiara", "apellido": "Leon", "genero": "Femenino", "correo": "nisl.sem@fringilla.org", "usuario": "Shana Powell", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 249, 5036 Cursus. Rd.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Willow", "apellido": "Oneill", "genero": "Masculino", "correo": "lectus@luctusutpellentesque.com", "usuario": "Wynter Wilkerson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 869, 8457 Vitae, St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Brent", "apellido": "Davenport", "genero": "Masculino", "correo": "Integer@adipiscingnonluctus.edu", "usuario": "Hakeem Peck", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "3814 Parturient St.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Herman", "apellido": "Calderon", "genero": "Helicóptero Apache de Combate", "correo": "pede.nec@lectuspedeultrices.edu", "usuario": "Moses Austin", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "6799 Lorem Av.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Nathaniel", "apellido": "Obrien", "genero": "Masculino", "correo": "nulla.Donec@ultriciesligulaNullam.net", "usuario": "Allegra Sawyer", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "1620 Nisi Ave", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Plato", "apellido": "Huber", "genero": "Femenino", "correo": "nisl.arcu@Nunc.edu", "usuario": "Quin Nguyen", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "1318 Penatibus Av.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Joel", "apellido": "Daugherty", "genero": "Helicóptero Apache de Combate", "correo": "nec@Duis.edu", "usuario": "Timon Beasley", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "6079 Duis St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Griffin", "apellido": "Schwartz", "genero": "Masculino", "correo": "blandit.viverra.Donec@temporaugue.com", "usuario": "Carter Campbell", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "8619 Posuere Ave", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Lamar", "apellido": "Farrell", "genero": "Masculino", "correo": "tempor.erat@dui.co.uk", "usuario": "Yoshi Stanley", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #650-4583 Penatibus Avenue", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Meredith", "apellido": "Cunningham", "genero": "Helicóptero Apache de Combate", "correo": "augue@Nullamsuscipit.ca", "usuario": "Jackson Olson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "4427 Enim Street", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Camden", "apellido": "Stewart", "genero": "Masculino", "correo": "fringilla@Nuncmaurissapien.edu", "usuario": "Malachi Yates", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "215-2909 Dolor Rd.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Ella", "apellido": "Marsh", "genero": "Helicóptero Apache de Combate", "correo": "adipiscing.ligula@enimmi.edu", "usuario": "Whitney Johns", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "7641 Dictum Ave", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Ivor", "apellido": "Levy", "genero": "Masculino", "correo": "amet@odioauctor.ca", "usuario": "Hayes Hoffman", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #776-2468 Tincidunt. Street", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Emerald", "apellido": "Trujillo", "genero": "Helicóptero Apache de Combate", "correo": "risus@Morbiquisurna.ca", "usuario": "Leonard Pearson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "863-8488 Tempus Street", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Chase", "apellido": "England", "genero": "Helicóptero Apache de Combate", "correo": "pede.et@dolor.edu", "usuario": "Melvin Wood", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "849-5375 Iaculis Avenue", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "James", "apellido": "Gordon", "genero": "Helicóptero Apache de Combate", "correo": "eget@etarcuimperdiet.edu", "usuario": "Brendan Greene", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 876, 479 Duis Av.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Vaughan", "apellido": "Andrews", "genero": "Masculino", "correo": "rutrum.eu@a.org", "usuario": "Ori Whitaker", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 893, 3581 Magna. Street", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Ross", "apellido": "Alexander", "genero": "Femenino", "correo": "quis@Mauris.org", "usuario": "Francis Terry", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "8282 Placerat Road", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Ingrid", "apellido": "Whitaker", "genero": "Femenino", "correo": "ac@eu.com", "usuario": "Kasper Kelly", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "447-862 Leo. Road", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Ronan", "apellido": "Boyle", "genero": "Helicóptero Apache de Combate", "correo": "amet@ridiculus.org", "usuario": "Tarik Flores", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 399, 7051 Iaculis Street", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Carl", "apellido": "Porter", "genero": "Femenino", "correo": "dolor@vehiculaaliquet.org", "usuario": "Hayden Watson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "6266 Ipsum. Avenue", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Ignatius", "apellido": "Cox", "genero": "Femenino", "correo": "mi.pede@tellusnon.edu", "usuario": "Wang Walsh", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "811-7566 Risus. Rd.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Nigel", "apellido": "Young", "genero": "Femenino", "correo": "Etiam.laoreet.libero@atarcuVestibulum.com", "usuario": "Tucker Hughes", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 730, 8743 Eu, Avenue", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Sawyer", "apellido": "Ortiz", "genero": "Masculino", "correo": "nisi.Cum.sociis@euligulaAenean.net", "usuario": "Bradley Dillon", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "439-1519 Vitae Rd.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Aiko", "apellido": "Kennedy", "genero": "Masculino", "correo": "purus@dictumultriciesligula.com", "usuario": "Wesley Mcneil", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 978, 8120 Senectus Rd.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Rhea", "apellido": "Le", "genero": "Masculino", "correo": "lobortis.quam@sed.net", "usuario": "Iliana Hawkins", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "8149 Venenatis Ave", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Wynne", "apellido": "Hatfield", "genero": "Helicóptero Apache de Combate", "correo": "Duis.elementum.dui@aliquetodio.com", "usuario": "Harper Patrick", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #353-5796 Nec Av.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Colby", "apellido": "Andrews", "genero": "Helicóptero Apache de Combate", "correo": "orci@dui.com", "usuario": "Raven Cain", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "437 At Road", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Dustin", "apellido": "Hamilton", "genero": "Masculino", "correo": "aliquet.magna@Quisquetinciduntpede.co.uk", "usuario": "Laurel Ochoa", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 500, 794 Enim St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Ulla", "apellido": "Powell", "genero": "Masculino", "correo": "sit.amet.lorem@urnaVivamus.org", "usuario": "Ann Garrett", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "851-4362 Et St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Mohammad", "apellido": "Baxter", "genero": "Helicóptero Apache de Combate", "correo": "Cras@Crasconvallisconvallis.edu", "usuario": "Iris Gould", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 916, 6077 Sit Road", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Quail", "apellido": "Osborne", "genero": "Masculino", "correo": "metus@Mauris.edu", "usuario": "Byron Small", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #961-8560 Neque St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Odette", "apellido": "Oneal", "genero": "Femenino", "correo": "risus@sodalesatvelit.edu", "usuario": "Keith Abbott", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "337-4156 Primis St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Jennifer", "apellido": "Landry", "genero": "Masculino", "correo": "mi.ac@lectuspede.org", "usuario": "Paula Paul", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 197, 760 Egestas St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Baker", "apellido": "Calhoun", "genero": "Masculino", "correo": "pellentesque.eget@atsemmolestie.net", "usuario": "Orli Ingram", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 254, 7607 Donec Av.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Nora", "apellido": "Austin", "genero": "Femenino", "correo": "id.sapien.Cras@accumsaninterdumlibero.ca", "usuario": "Jaime Farley", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "371-6111 Non, Road", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Amir", "apellido": "Schwartz", "genero": "Helicóptero Apache de Combate", "correo": "eu@nulla.ca", "usuario": "Orson Lowe", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 484, 3032 Fusce St.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Hall", "apellido": "Hardin", "genero": "Helicóptero Apache de Combate", "correo": "eu.dui.Cum@euaccumsansed.com", "usuario": "Elijah Kent", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "842-2204 Congue Road", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Jeremy", "apellido": "Ramos", "genero": "Helicóptero Apache de Combate", "correo": "egestas.hendrerit@luctusfelispurus.com", "usuario": "Lydia Booth", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #749-3570 At Road", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Zephania", "apellido": "Hughes", "genero": "Femenino", "correo": "cursus@non.com", "usuario": "Darius Meadows", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "3226 Lacinia Rd.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Odessa", "apellido": "Marsh", "genero": "Femenino", "correo": "libero.Donec@eu.edu", "usuario": "Ginger Stark", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #535-8878 Sed St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Harding", "apellido": "Brewer", "genero": "Femenino", "correo": "Sed@magnatellus.ca", "usuario": "Ila Fletcher", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "8836 Ac Road", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Steven", "apellido": "Levine", "genero": "Masculino", "correo": "et.libero@facilisisfacilisismagna.com", "usuario": "Emma Frederick", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 451, 3987 Fermentum Av.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Martin", "apellido": "Ayers", "genero": "Helicóptero Apache de Combate", "correo": "augue@acorciUt.edu", "usuario": "Mira Everett", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 521, 239 In Street", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Yoko", "apellido": "Martin", "genero": "Helicóptero Apache de Combate", "correo": "imperdiet@ornareIn.edu", "usuario": "Zenia Alford", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "8948 Cursus. Rd.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Noelle", "apellido": "Shaw", "genero": "Helicóptero Apache de Combate", "correo": "tellus.non@Mauris.net", "usuario": "Judith Raymond", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "9190 Ut, Road", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Gary", "apellido": "Atkinson", "genero": "Helicóptero Apache de Combate", "correo": "pellentesque@non.ca", "usuario": "Alma Logan", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 941, 6919 Sagittis Ave", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Catherine", "apellido": "Hoffman", "genero": "Helicóptero Apache de Combate", "correo": "tristique@eu.ca", "usuario": "Marshall Boone", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #235-1677 Vestibulum St.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Sydnee", "apellido": "Hendricks", "genero": "Helicóptero Apache de Combate", "correo": "accumsan.sed.facilisis@euismodenimEtiam.co.uk", "usuario": "Macaulay Flores", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "8496 Donec Road", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Anika", "apellido": "Higgins", "genero": "Masculino", "correo": "senectus@accumsansed.org", "usuario": "Octavia Evans", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "661-9781 Nunc Rd.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Medge", "apellido": "Stephens", "genero": "Femenino", "correo": "tellus.eu@libero.ca", "usuario": "Amir Lucas", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 810, 4087 Duis St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Martena", "apellido": "Wolfe", "genero": "Helicóptero Apache de Combate", "correo": "eros.Proin.ultrices@ridiculusmusDonec.co.uk", "usuario": "Ivory Kirby", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "618-6366 Non Road", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Nathan", "apellido": "Blair", "genero": "Helicóptero Apache de Combate", "correo": "bibendum.ullamcorper.Duis@congue.ca", "usuario": "Wyoming Orr", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "579-2937 Montes, St.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Hyacinth", "apellido": "Fuentes", "genero": "Femenino", "correo": "dolor@tempuslorem.com", "usuario": "Jesse White", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "118-1018 Ante. Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Forrest", "apellido": "Massey", "genero": "Masculino", "correo": "dapibus.quam.quis@estNuncullamcorper.net", "usuario": "Emi Tyler", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #707-4936 Orci, St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Merritt", "apellido": "Huffman", "genero": "Masculino", "correo": "lobortis@inmagna.edu", "usuario": "Zahir Lindsay", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #926-1387 Porttitor St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Cleo", "apellido": "Morris", "genero": "Helicóptero Apache de Combate", "correo": "quis@tellusimperdiet.co.uk", "usuario": "Ria Avery", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 571, 7947 Vestibulum Road", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Ria", "apellido": "Horn", "genero": "Masculino", "correo": "metus.sit@consequatlectus.org", "usuario": "Reagan Maxwell", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #972-3789 Fermentum Av.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Dane", "apellido": "Neal", "genero": "Masculino", "correo": "Integer.vulputate.risus@Proindolor.edu", "usuario": "Eve Whitehead", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "125-5447 Malesuada Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Germaine", "apellido": "Powers", "genero": "Masculino", "correo": "neque.non.quam@sagittissemperNam.co.uk", "usuario": "Hedley Sharp", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #179-6730 Sed Rd.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Kermit", "apellido": "York", "genero": "Helicóptero Apache de Combate", "correo": "eros@infaucibus.co.uk", "usuario": "Malik Suarez", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #826-9642 Scelerisque Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Ashton", "apellido": "Hickman", "genero": "Femenino", "correo": "arcu@sitametluctus.edu", "usuario": "Mark Hutchinson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #594-3377 Quis Avenue", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Claudia", "apellido": "Bass", "genero": "Masculino", "correo": "Aliquam@erosProinultrices.net", "usuario": "Aubrey Cross", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "323-1285 Tempus St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Ivory", "apellido": "Waller", "genero": "Femenino", "correo": "mollis@magnaSuspendissetristique.co.uk", "usuario": "Damian Carey", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "5619 Pellentesque, Av.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Tara", "apellido": "Bird", "genero": "Masculino", "correo": "amet.consectetuer.adipiscing@idmollis.edu", "usuario": "Forrest Marks", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #186-6367 Ultrices St.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Wade", "apellido": "Nixon", "genero": "Femenino", "correo": "placerat.velit@varius.org", "usuario": "Dennis Erickson", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "949-4434 Euismod Rd.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Scott", "apellido": "Gibson", "genero": "Masculino", "correo": "Cum.sociis@adipiscingfringillaporttitor.com", "usuario": "Chloe Workman", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "Ap #966-9293 Faucibus Ave", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Samuel", "apellido": "Roberts", "genero": "Helicóptero Apache de Combate", "correo": "eget.ipsum@Ut.edu", "usuario": "Alexander Buchanan", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 745, 1713 Tempus St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Brenda", "apellido": "Rodriquez", "genero": "Masculino", "correo": "blandit.at.nisi@urnaVivamus.net", "usuario": "Duncan Moran", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "1018 A, Avenue", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Ulysses", "apellido": "Simon", "genero": "Helicóptero Apache de Combate", "correo": "magna.tellus.faucibus@et.ca", "usuario": "TaShya Miles", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 670, 2030 Dignissim Ave", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Coby", "apellido": "Scott", "genero": "Femenino", "correo": "tempor.arcu@quis.edu", "usuario": "Macaulay Puckett", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "1656 Erat St.", "plan_activo": "5cc77af9fb6fc00ed59db713"},
            {"nombre": "Dominique", "apellido": "Figueroa", "genero": "Femenino", "correo": "libero.est@est.edu", "usuario": "Clare David", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "928-9244 Sollicitudin Road", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Phelan", "apellido": "Mason", "genero": "Femenino", "correo": "nibh.Quisque.nonummy@Fuscedolorquam.ca", "usuario": "Adam Huber", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "2580 At Rd.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Holmes", "apellido": "Puckett", "genero": "Femenino", "correo": "Sed.dictum.Proin@adipiscingligulaAenean.ca", "usuario": "Chadwick Potts", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 430, 2897 Orci, Rd.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Veda", "apellido": "Beasley", "genero": "Femenino", "correo": "est@tristiquesenectuset.co.uk", "usuario": "Dolan Gay", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "859-1358 Enim. St.", "plan_activo": "5cc77b5bfb6fc00ed59db754"},
            {"nombre": "Tanek", "apellido": "Powers", "genero": "Helicóptero Apache de Combate", "correo": "Vivamus.nibh.dolor@Donecdignissim.com", "usuario": "Hilda Norman", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "8559 Purus St.", "plan_activo": "5cc77b39fb6fc00ed59db736"},
            {"nombre": "Evan", "apellido": "Hutchinson", "genero": "Masculino", "correo": "diam.lorem.auctor@egettinciduntdui.ca", "usuario": "Pearl Cain", "contrasenia": "asd.456", "foto_perfil": "img/Logo-GEPO-page.svg", "residencia": "P.O. Box 578, 668 Eget Av.", "plan_activo": "5cc77b39fb6fc00ed59db736"}
        ];

        for(var i=0; i<data.length; i++){
            user = new usuarioModel({
              nombre : data[i].nombre,
              apellido : data[i].apellido,
              foto_perfil : data[i].foto_perfil,
              genero : data[i].genero,
              residencia : data[i].residencia,
              correo : data[i].correo,
              usuario : data[i].usuario,
              contrasenia : data[i].contrasenia,
              amigos: [],
              plan_activo: mongoose.Types.ObjectId(plan_activo)
            });

            user.save()
            .then(()=>{
              console.log(`Dato ${i} registrado`);
            })
        }
    }
}

module.exports = new Database();